#!/usr/bin/env python

"""
========================
psmc_check
========================

This code generates backstop load review outputs for checking the ACIS
PSMC temperature 1PDEAAT.  It also generates PSMC model validation
plots comparing predicted values to telemetry for the previous three
weeks.
"""

import sys
# Matplotlib setup
# Use Agg backend for command-line (non-interactive) operation
import matplotlib
if __name__ == '__main__':
    matplotlib.use('Agg')
from acis_thermal_check import psmc_check, get_options

if __name__ == '__main__':
    dhh_opt = {"type": "int", "default":0,
               "help": "Starting Detector Housing Heater state"}
    opt, args = get_options("1PDEAAT", "psmc", [("dh_heater", dhh_opt)])
    try:
        psmc_check.driver(opt)
    except Exception, msg:
        if opt.traceback:
            raise
        else:
            print "ERROR:", msg
            sys.exit(1)
